# Generated by Django 5.0.3 on 2024-03-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
